runtime: python312
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 20
entrypoint: gunicorn -b :$PORT app:app
env_variables:
  FLASK_APP: "app.py"
  FLASK_ENV: "production"
  PYTHONPATH: "C:\Python312"
