runtime: python312 # replace with your Python version
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
resources:
  cpu: 2
  memory_gb: 1
  disk_size_gb: 20 # adjust as needed
entrypoint: gunicorn -b :$PORT app:app # replace with your entrypoint
env_variables:
  FLASK_APP: "app.py" # replace with your Flask app file
  FLASK_ENV: "production"
