const subCategories = {
  A: [
    "A1: Sore Throat / Hoarseness",
    "A2: Ear Pain/Drainage / Trauma",
    "A3: Cold Symptoms / Allergies / Cough",
    "A4: Ringing in the Ears / Hearing Problem",
    "A5: Nosebleed / Nose Trauma",
  ],
  B: [
    "B1: Back Pain",
    "B2: Neck Pain",
    "B3: Shoulder Pain",
    "B4: Elbow Pain",
    "B5: Wrist Pain",
    "B6: Hand Pain",
    "B7: Hip Pain",
    "B8: Knee Pain",
    "B9: Ankle Pain",
    "B10: Foot Pain",
    "B11: Extremity, Non-joint Pain",
  ],
  C: [
    "C1: Nausea / Vomiting",
    "C2: Diarrhea",
    "C3: Abdominal and Flank Pain",
    "C4: Rectal Pain / Itching / Bleeding",
    "C5: Constipation",
    "C6: Difficulty When Swallowing",
    "C7: Heartburn",
  ],
  D: ["D1: Shortness of Breath", "D2: Chest Pain"],
  E: [
    "E1: Painful / Frequent Urination",
    "E2: Groin / Testicular Pain or Urethral Discharge",
    "E3: Sexually Transmitted Infection (STI)",
    "E4: Problems with Voiding",
  ],
  F: [
    "F1: Dizziness / Faintness / Blackout",
    "F2: Headache",
    "F3: Numbness / Tingling / Paralysis / Weakness",
    "F4: Drowsiness / Confusion",
    "F5: Depression / Nervousness / Anxiety / Tension",
    "F6: Minor Traumatic Brain Injury",
  ],
  G: ["G1: Fatigue", "G2: Fever / Chills"],
  H: [
    "H1: Eye Pain / Redness / Discharge / Itching / Injury",
    "H2: Eyelid Problem",
    "H3: Decreased Vision, Seeing Spots, Request for Glasses",
    "H4: Seeing Double (Diplopia)",
  ],
  I: [
    "I1: Breast Problems",
    "I2: Suspects Pregnancy",
    "I3: Menstrual Problems, Vaginal Bleeding",
    "I4: Vaginal Discharge, Itching, Irritation, or Pain",
    "I5: Request for PAP or Routine Pelvic Examination",
    "I6: Request for Information on Contraception",
  ],
  J: [
    "J1: Unknown Cause of Skin Disorder / Complaint",
    "J2: Acne",
    "J3: Pseudofolliculitis Barbae (Ingrown Hairs)",
    "J4: Dandruff (Scaling of the Scalp)",
    "J5: Hair Loss",
    "J6: Athlete's Foot (Tinea Pedis)",
    "J7: Jock Itch (Tinea Cruris)",
    "J8: Scaling, Depigmented Spots (Tinea Versicolor)",
    "J9: Boils",
    "J10: Fever Blisters (Cold Sores)",
    "J11: Skin Abrasion / Laceration",
    "J12: Suture Removal",
    "J13: Drug Rash, Contact Dermatitis",
    "J14: Burns / Sunburn",
    "J15: Friction Blisters on Feet",
    "J16: Corns on Feet",
    "J17: Cutaneous (Plantar) Warts",
    "J18: Ingrown Toenail",
  ],
  K: [
    "K1: Exertional Heat Illness",
    "K2: Hypothermia",
    "K3: Immersion Foot",
    "K4: Chapped Skin / Windburn",
    "K5: Frostbite",
    "K6: Crabs / Lice (Pediculosis)",
    "K7: Insect Bites (Not Crabs / Lice)",
  ],
  L: [
    "L1: Exposed to Hepatitis or HIV",
    "L2: Dental Problems",
    "L3: Sores in the Mouth",
    "L4: Prescription Refill",
    "L5: Requests a Vasectomy",
    "L6: Needs an Immunization",
    "L7: Lymph Node Enlargement",
    "L8: Blood Pressure Check",
    "L9: Medical Screening for Overseas PCS",
    "L10: Weight Reduction",
    "L11: Complain Not on the List",
    "L12: Request for Nonprescription or Traveling Medication",
  ],
  M: ["M1: No Signs of Improvement", "M2: Return Requested by Provider"],
};

export default subCategories;
